import { ROLES } from "@/constants/roles";

import type { UserRole } from "@/types";

import {
    PERMISSIONS,
    type Permission,
} from "./permissions";

export const ROLE_PERMISSIONS: Record<
    UserRole,
    Permission[]
> = {

    [ROLES.ADMIN]: [

        PERMISSIONS.MEMBERS_VIEW,
        PERMISSIONS.MEMBERS_CREATE,
        PERMISSIONS.MEMBERS_EDIT,
        PERMISSIONS.MEMBERS_DELETE,

        PERMISSIONS.CONTRIBUTIONS_VIEW,
        PERMISSIONS.CONTRIBUTIONS_CREATE,
        PERMISSIONS.CONTRIBUTIONS_EDIT,

        PERMISSIONS.ACCOUNTING_VIEW,
        PERMISSIONS.ACCOUNTING_CREATE,
        PERMISSIONS.ACCOUNTING_EDIT,

        PERMISSIONS.EVENTS_VIEW,
        PERMISSIONS.EVENTS_CREATE,

        PERMISSIONS.INVITATIONS_CREATE,

        PERMISSIONS.SETTINGS_MANAGE,

    ],

    [ROLES.TREASURER]: [

        PERMISSIONS.CONTRIBUTIONS_VIEW,
        PERMISSIONS.CONTRIBUTIONS_CREATE,
        PERMISSIONS.CONTRIBUTIONS_EDIT,

        PERMISSIONS.ACCOUNTING_VIEW,
        PERMISSIONS.ACCOUNTING_CREATE,
        PERMISSIONS.ACCOUNTING_EDIT,

        PERMISSIONS.EVENTS_VIEW,

    ],

    [ROLES.MEMBER]: [

        PERMISSIONS.CONTRIBUTIONS_VIEW,

        PERMISSIONS.EVENTS_VIEW,

    ],

};